# Ex1: Vectors

## Câu 1: 
- Viết function cal_vectors(op, u, v) với op là một trong các toán tử +, -, *, /, "dot"; u và v là vector (numpy array). Hãy thực hiện việc tính toán theo toán tử và hai vector được truyền vào. Kết quả trả về là một vector/giá trị tương ứng.
- Gọi function này với các toán tử khác nhau để xem kết quả

## Câu 2: Vector Norm
- Viết function cal_vector_norm(t, v) với t là một trong các loại L1, L2, Max; v là vector. Hãy thực hiện việc tính toán theo loại và vector được truyền vào. Kết quả trả về là một giá trị tương ứng.
- Gọi function này với các loại khác nhau để xem kết quả

## Câu 1: Gợi ý

In [1]:
import numpy as np

In [2]:
def cal_vectors(op, u, v):
    result = None
    if op == "+":
        result = u + v
    elif op == "-":
        result = u - v
    elif op == "*":
        result = u * v
    elif op == "/":
        result = u / v
    elif op=="dot":
        result = u.dot(v)
    else: 
        result = None
    return result

In [3]:
u = np.array([1, 3, 4, 6, 3, 4, 5])
v = np.array([4, 7, 1, 2, 3, 8, 9])

In [4]:
cal_vectors("+", u, v)

array([ 5, 10,  5,  8,  6, 12, 14])

In [5]:
cal_vectors("-", u, v)

array([-3, -4,  3,  4,  0, -4, -4])

In [6]:
cal_vectors("*", u, v)

array([ 4, 21,  4, 12,  9, 32, 45])

In [7]:
cal_vectors("/", u, v)

array([0.25      , 0.42857143, 4.        , 3.        , 1.        ,
       0.5       , 0.55555556])

In [8]:
cal_vectors("dot", u, v)

127

In [9]:
cal_vectors("%", u, v)

## Câu 2: Vector Norm (gợi ý)
- Viết function cal_vector_norm(t, v) với t là một trong các loại L1, L2, Max; v là vector. Hãy thực hiện việc tính toán theo loại và vector được truyền vào. Kết quả trả về là một giá trị tương ứng.
- Gọi function này với các loại khác nhau để xem kết quả

In [10]:
import numpy as np
from numpy.linalg import norm
import math

In [11]:
def cal_vector_norm(t, v):
    result = None
    if t == "L1":
        result = norm(v,1)
    elif t =="L2":
        result = norm(v)
    elif t == "Max":
        result = norm(v, math.inf)
    else:
        result = None
    return result        

In [12]:
v = np.array([1, 3, -4, 5, 7, 9, -6])

In [13]:
cal_vector_norm("L1", v)

35.0

In [14]:
cal_vector_norm("L2", v)

14.730919862656235

In [15]:
cal_vector_norm("Max", v)

9.0

In [16]:
cal_vector_norm("Min", v)