In [15]:
import numpy as np
from numpy.linalg import norm
import math
from numpy import tril, triu

In [2]:
u = np.array([3, 1, 2])
v = np.array([1, 0, 4])

c = u.dot(v)
c

11

In [3]:
L1 = norm(u, 1)
L1

6.0

In [4]:
L2 = norm(u)
L2

3.7416573867739413

In [5]:
max_norm = norm(u, math.inf)
max_norm

3.0

In [11]:
A = np.array(
[[1, 2],
 [7, 5],
 [2, 3]])
B = np.array(
[[2, 5],
 [3, 1]])
C = A @ B
C

array([[ 8,  7],
       [29, 40],
       [13, 13]])

In [14]:
D = A.dot(2)
D

array([[ 2,  4],
       [14, 10],
       [ 4,  6]])

In [20]:
d = np.diag(A)
print(d)
di = np.diag(d)
print(di)

[1 5]
[[1 0]
 [0 5]]


In [21]:
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
At = A.transpose()
At

array([[1, 7, 2],
       [2, 5, 3]])

In [33]:
C = np.array(
[[1, 2, 3],
 [7, 5, 4],
 [2, 3, 5]])
Ci = np.linalg.inv(C)
print(Ci)

R = C @ Ci
print(R)

[[-1.625  0.125  0.875]
 [ 3.375  0.125 -2.125]
 [-1.375 -0.125  1.125]]
[[ 1.00000000e+00  8.32667268e-17 -6.66133815e-16]
 [ 3.55271368e-15  1.00000000e+00  0.00000000e+00]
 [ 4.44089210e-16  2.77555756e-17  1.00000000e+00]]


In [35]:
detC = np.linalg.det(C)
detC

-7.999999999999995