In [29]:
import numpy as np
from numpy.linalg import norm, cholesky, eig
import math
from numpy import tril, triu
from scipy.linalg import lu

In [2]:
u = np.array([3, 1, 2])
v = np.array([1, 0, 4])

c = u.dot(v)
c

11

In [3]:
L1 = norm(u, 1)
L1

6.0

In [4]:
L2 = norm(u)
L2

3.7416573867739413

In [5]:
max_norm = norm(u, math.inf)
max_norm

3.0

In [6]:
A = np.array(
[[1, 2],
 [7, 5],
 [2, 3]])
B = np.array(
[[2, 5],
 [3, 1]])
C = A @ B
C

array([[ 8,  7],
       [29, 40],
       [13, 13]])

In [7]:
D = A.dot(2)
D

array([[ 2,  4],
       [14, 10],
       [ 4,  6]])

In [8]:
d = np.diag(A)
print(d)
di = np.diag(d)
print(di)

[1 5]
[[1 0]
 [0 5]]


In [9]:
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
At = A.transpose()
At

array([[1, 7, 2],
       [2, 5, 3]])

In [11]:
C = np.array(
[[1, 2, 3],
 [7, 5, 4],
 [2, 3, 5]])
Ci = np.linalg.inv(C)
print(Ci)

R = C @ Ci
print(R)

[[-1.625  0.125  0.875]
 [ 3.375  0.125 -2.125]
 [-1.375 -0.125  1.125]]
[[ 1.00000000e+00  2.77555756e-17 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00 -8.88178420e-16]
 [ 8.88178420e-16 -2.77555756e-17  1.00000000e+00]]


In [12]:
detC = np.linalg.det(C)
detC

-7.999999999999995

In [13]:
P, L, U = lu(C)

print('P: ', P)
print('L: ', L)
print('U: ', U)

F = P.dot(L).dot(U)
print('F: ', F)


P:  [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L:  [[1.         0.         0.        ]
 [0.28571429 1.         0.        ]
 [0.14285714 0.81818182 1.        ]]
U:  [[ 7.          5.          4.        ]
 [ 0.          1.57142857  3.85714286]
 [ 0.          0.         -0.72727273]]
F:  [[1. 2. 3.]
 [7. 5. 4.]
 [2. 3. 5.]]


In [28]:
Ch = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
print('Ch: \n', Ch)
L = cholesky(Ch)
print('L: \n', L)

Ch: 
 [[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
L: 
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [23]:
R = L.dot(L.transpose())
R

array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

In [32]:
A = np.array([[2, 3], [4, 1]])

values, vectors = eig(A)
print('values\n', values)
print('vectors\n', vectors)

values
 [ 5. -2.]
vectors
 [[ 0.70710678 -0.6       ]
 [ 0.70710678  0.8       ]]


In [61]:
A @ vectors[:, 0]

array([3.53553391, 3.53553391])

In [65]:
values[0] * vectors[:, 0]

array([3.53553391, 3.53553391])

In [77]:
B = np.array([[2, 3], [4, 1]])
A = B @ B.T
values, vectors = eig(A)
vectors @ vectors.T

array([[1., 0.],
       [0., 1.]])