# Ex1: Tính toán 
- Tạo một ma trận A(3000, 3) có các giá trị ngẫu nhiên từ 1 đến 255
- Áp dụng tính toán PCA
- Trực quan hóa kết quả

In [1]:
import numpy as np

In [2]:
A = np.random.randint(1,256,(3000,3))
A.shape


(3000, 3)

In [3]:
A[0:10]

array([[143, 253, 146],
       [ 43, 247, 156],
       [161, 113,   9],
       [  9,  44,  48],
       [192,  92,  18],
       [  2, 151, 186],
       [153, 167,  90],
       [214,  66,  42],
       [152, 213,  25],
       [122, 228,   7]])

In [5]:
# colmns' means
M = np.mean(A.T, axis = 1)
M

array([126.801     , 129.55366667, 129.83633333])

In [6]:
M1 = np.mean(A, axis = 0)
M1

array([126.801     , 129.55366667, 129.83633333])

In [7]:
# center columns by subtracting column means
C = A - M
C[0:10]

array([[  16.199     ,  123.44633333,   16.16366667],
       [ -83.801     ,  117.44633333,   26.16366667],
       [  34.199     ,  -16.55366667, -120.83633333],
       [-117.801     ,  -85.55366667,  -81.83633333],
       [  65.199     ,  -37.55366667, -111.83633333],
       [-124.801     ,   21.44633333,   56.16366667],
       [  26.199     ,   37.44633333,  -39.83633333],
       [  87.199     ,  -63.55366667,  -87.83633333],
       [  25.199     ,   83.44633333, -104.83633333],
       [  -4.801     ,   98.44633333, -122.83633333]])

In [8]:
# calculate covariance matrix of centered matrix
V = np.cov(C.T)

In [ ]:
V[0:10]

array([[5364.74885895,  -28.23721374,   68.36283228],
       [ -28.23721374, 5350.19632277,   17.9505962 ],
       [  68.36283228,   17.9505962 , 5439.07118273]])

In [9]:
# factorize covariance matrix
values, vectors = np.linalg.eig(V)
values

array([5404.2070463 , 5554.90850032, 5617.48005069])

In [10]:
vectors[0:10]

array([[ 0.35173475,  0.85743292,  0.37562143],
       [ 0.52054951,  0.15434286, -0.83976573],
       [ 0.77801727, -0.49090434,  0.39204854]])

In [11]:
# project data
P = vectors.T.dot(C.T)
print(P.T)                                                            

[[  82.53329189   25.00780233  -91.24436688]
 [  52.0166929   -66.57059016 -119.8474299 ]
 [ -90.60078064   86.08748836  -20.62662914]
 ...
 [  51.79830577   76.05593073   87.23378085]
 [-157.89894885  -19.03052199   37.41784049]
 [  80.55561364 -134.82208907  -70.64110002]]


In [12]:
P = C.dot(vectors)
print(P)                                                            

[[  82.53329189   25.00780233  -91.24436688]
 [  52.0166929   -66.57059016 -119.8474299 ]
 [ -90.60078064   86.08748836  -20.62662914]
 ...
 [  51.79830577   76.05593073   87.23378085]
 [-157.89894885  -19.03052199   37.41784049]
 [  80.55561364 -134.82208907  -70.64110002]]
