# Ex1: Tính toán 
- Tạo một ma trận A(3000, 3) có các giá trị ngẫu nhiên từ 1 đến 255
- Áp dụng tính toán PCA
- Trực quan hóa kết quả

In [2]:
import numpy as np

In [3]:
A = np.random.randint(1,256,(3000,3))
A.shape


(3000, 3)

In [4]:
A[0:10]

array([[ 35, 191, 255],
       [  7,  30, 133],
       [117,  91, 167],
       [ 94, 202, 102],
       [227,  25,  90],
       [200, 229, 143],
       [ 14,  16, 254],
       [212, 136,  37],
       [ 35,  67,  81],
       [ 20, 114, 212]])

In [5]:
# colmns' means
M = np.mean(A.T, axis = 1)
M

array([126.54133333, 127.91      , 128.87766667])

In [6]:
M1 = np.mean(A, axis = 0)
M1

array([126.54133333, 127.91      , 128.87766667])

In [7]:
# center columns by subtracting column means
C = A - M
C[0:10]

array([[ -91.54133333,   63.09      ,  126.12233333],
       [-119.54133333,  -97.91      ,    4.12233333],
       [  -9.54133333,  -36.91      ,   38.12233333],
       [ -32.54133333,   74.09      ,  -26.87766667],
       [ 100.45866667, -102.91      ,  -38.87766667],
       [  73.45866667,  101.09      ,   14.12233333],
       [-112.54133333, -111.91      ,  125.12233333],
       [  85.45866667,    8.09      ,  -91.87766667],
       [ -91.54133333,  -60.91      ,  -47.87766667],
       [-106.54133333,  -13.91      ,   83.12233333]])

In [8]:
# calculate covariance matrix of centered matrix
V = np.cov(C.T)

In [9]:
V[0:10]

array([[5375.01196221,   65.32316105,  -22.19484184],
       [  65.32316105, 5399.72314105,   87.66454485],
       [ -22.19484184,   87.66454485, 5533.79329899]])

In [10]:
# factorize covariance matrix
values, vectors = np.linalg.eig(V)
values

array([5296.55441122, 5434.40750523, 5577.5664858 ])

In [11]:
vectors[0:10]

array([[-0.65835763,  0.75105726,  0.04978178],
       [ 0.68393557,  0.56928003,  0.4562372 ],
       [-0.31432049, -0.33441477,  0.88846462]])

In [15]:
# project data
# P = vectors.T.dot(C.T)
P = vectors.T @ C.T
print(P.T)                                                            

[[  63.77359621  -75.01407736  136.28214629]
 [  10.44108289 -146.89916322  -46.95861733]
 [ -30.9450829   -40.92688489   16.5556449 ]
 ...
 [   0.99602728    4.95523285  128.41536397]
 [  65.90849654  -30.72737683   18.64231309]
 [ -62.55983691   65.20451457 -114.5078259 ]]


In [13]:
P = C.dot(vectors)
print(P)                                                            

[[  63.77359621  -75.01407736  136.28214629]
 [  10.44108289 -146.89916322  -46.95861733]
 [ -30.9450829   -40.92688489   16.5556449 ]
 ...
 [   0.99602728    4.95523285  128.41536397]
 [  65.90849654  -30.72737683   18.64231309]
 [ -62.55983691   65.20451457 -114.5078259 ]]
